// First test
export const FETCH_USER_DATABASE_ADMIN = "FETCH_USER_DATABASE_ADMIN";
export const FETCH_USERS_ERRANDS = "FETCH_USERS_ERRANDS";
export const FETCH_USERS_ERRAND_DETAILS = "FETCH_USERS_ERRAND_DETAILS";

export const FETCH_USER_DATABASE = "FETCH_USER_DATABASE";
export const FETCH_CURRENT_ERRAND = "FETCH_CURRENT_ERRAND";